# Generated by Django 2.2.1 on 2019-05-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='create_date',
            field=models.DateField(editable=False),
        ),
    ]
